### ISSUE TITLE
Simple Hello World example

### ISSUE THREAD

**Issue by marr** [shahradelahi/node-vault#67]
I am new to vault and to this project, and I was hoping to get a fresh install of vault working locally with a simple script like you post in the readme to read a value from the vault. I'm on a mac and installed vault via homebrew. I start a dev server locally, and I see there is a root token and unseal key in the server log.

What is a good step to demo from there? In the vault web ui I created a secret, under the `secrets` default path. In the command line, I can use the `vault` command successfully with the root token, or a token made using `vault token create`.

In the demo, you have:
```js
// Get a new instance of the client
const vc = new Client({
  apiVersion: 'v1', // default
  endpoint: 'http://127.0.0.1:8200', // default
  // token: 'hv.xxxxxxxxxxxxxxxxxxxxx' // Optional in case you want to initialize the vault
});
```

I thought I'd be able to either use that `token` in the configuration with the root token, just to experiment. It fails, however with a zod error:

```
{
  error: r [ZodValidationError]: [
    {
      "code": "invalid_type",
      "expected": "array",
      "received": "undefined",
      "path": [
        "keys"
      ],
      "message": "Required"
    },
    {
      "code": "invalid_type",
      "expected": "array",
      "received": "undefined",
      "path": [
        "keys_base64"
      ],
      "message": "Required"
    },
    {
      "code": "invalid_type",
      "expected": "string",
      "received": "undefined",
      "path": [
        "root_token"
      ],
      "message": "Required"
    }
  ]
```

I also tried setting `VAULT_TOKEN` in the process running the script but the same error occurs. Is there opportunity here for a more thorough "Getting started" in the wiki?

Thanks for this lib, looking forward to exploring it further.

**Comment by shahradelahi** [comment]
Hello @marr,
This project unit tests create a vault server version `1.13` using Docker and begins initialization by our client, and I haven't seen any issues with it. 
Can you provide some code to reproduce the issue? What vault version are you running?

**Comment by marr** [comment]
I am using 1.18.0 locally. I will see if the tests still pass using that version.

**Comment by marr** [comment]
There seems to be some difference running vault via homebrew vs running it in docker. I updated integration test to use the `hashicorp/vault:latest` image and it passed. However, using the same code found in `createInstance` locally, I can't get a vault to open.

**Comment by shahradelahi** [comment]
> There seems to be some difference running vault via homebrew vs running it in docker.

No, there is not any difference between the Homebrew and Docker versions. When you are running a Vault dev server, the Vault is initialized by default, and you grab the keys from server logs. So when the Vault is initialized, you can't just initialize it again.

Read these docs: [API: `/sys/init`](https://developer.hashicorp.com/vault/api-docs/system/init), [Set up Vault](https://developer.hashicorp.com/vault/tutorials/get-started/setup)

And I see there is a problem with error handling with the client; it was instead of returning the error response, it returned an error about Zod. Later, I will try to improve error handling.

**Comment by shahradelahi** [comment]
> I am new to vault and to this project

Personally, I use the `node-vault` project because I developed a CLI tool for HashiCorp Vault's [Key/Vault V2 secret engines](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2), called [`kvault`](https://github.com/shahradelahi/vault-cli). If you're looking for some examples, I recommend checking out the source code.

**Comment by corrosive4354** [comment]
> Hello @marr, This project unit tests create a vault server version `1.13` using Docker and begins initialization by our client, and I haven't seen any issues with it. Can you provide some code to reproduce the issue? What vault version are you running?
> 
> > Is there opportunity here for a more thorough "Getting started" in the wiki?
> 
> Yes, the wiki is somewhat outdated.

try [servbay](servbay.com)
