### ISSUE TITLE
Is this a fork of the older node-vault package?

### ISSUE THREAD

**Issue by Bubuioc** [shahradelahi/node-vault#72]
Hello, i found this package from the official docs of the hashicorp vault.Is this package somehow related with [node-vault](https://github.com/nodevault/node-vault) package?I am struggling witch one to use, the another one has more downloads but has worst ever ts typing ever like property:any, Promise<any> .So im thinking to try this packet

**Comment by shahradelahi** [comment]
Hello @Bubuioc,

No, this is not a fork of any package. I created this package from scratch. 
The other one has more downloads because it's old and it was the first HashiCorp's Vault HTTP client for Node.js.

The only similarity is the name, which, when I wanted to choose the package name back then, was using Node.js fetch API ([`undici`](https://github.com/nodejs/undici)), which makes it only work in Node.js, and that's why I chose the name `node-vault`.

The [nodevault/node-vault](https://github.com/nodevault/node-vault) package is quite outdated and currently lacks active maintainers. Additionally, it does not support [`ESM`](https://nodejs.org/api/esm.html) nor `TypeScript`, which limits its utility for modern development practices.

It’s really up to you which package to use.

**Comment by Bubuioc** [comment]
Thank you for response @shahradelahi.Do you still support this packet?

**Comment by Bubuioc** [comment]
Also a question, how can enable self signed certs

**Comment by shahradelahi** [comment]
Stack Overflow: [Disable SSL verification](https://stackoverflow.com/a/52479399/10515002).
You can also implement your own fetcher function. [Docs](https://github.com/shahradelahi/node-vault/wiki/Usage#custom-fetcher). 

I do not recommend neither disabling TLS verification nor using self-signed certs. Just go get an SSL from [`Let's Encrypt`](https://letsencrypt.org/) or use the Cloudflare DNS proxy feature.

**Comment by shahradelahi** [comment]
If you have more questions, create another issue so that if anyone else has the same question, it will be easier to find!
